#!/bin/bash
#
#SBATCH --job-name=alyatest
#SBATCH --output=out_%j.out
#SBATCH --error=err_%j.out
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --cpus-per-task=1
#SBATCH --qos=bsc_case
#SBATCH --time=06:00:00


module load python/3-intel-2021.3
module load intel/2018.4 
module load impi/2018.4


srun python3 parallel.py
