#!/bin/bash
#SBATCH --job-name=TensP_PyLight
#SBATCH -D .
#SBATCH --output=out_%j.out
#SBATCH --error=out_%j.err
#SBATCH --ntasks=1
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=16
#SBATCH --qos=bsc_case
#SBATCH --time=10:00:00

module load gcc python/3.9.1 rocm/5.1.1
source /apps/RAY/ray/bin/activate

export PYTHONPATH="$PYTHONPATH:/home/bsc21/bsc21566/scratch/tmp/tensorporosity/ai-model"

srun python3 -u model_train_surrogate.py --model cnnSurr-te --data surrDS-te_amd.bin --epochs 4000 --trials 16 --num_cpus 16 --num_gpus 1 --db_path ../../surrogate_DS
